simulator:
  output_file : './report.json'
  silent_mode : false
  epochs : 100
  function_duration : 1
  seed : -1 # if seed is -1 then ignore it
  use_padding : true

events:
  generator_trigger_probability: 0.3
  event_min_probability: 0.3
  event_max_probability: 1


infrastructure:
  type: physical # allowed values are 'logical' and 'physical'
  filename: simple_infrastructure.pl
  is_dynamic: true # iff the infrastructure is dynamic, nodes and links can crash
  crash_probability :
    cloud : 0.001
    fog : 0.05
    edge : 0.1
  resurrection_probability :
    cloud : 0.5
    fog : 0.4
    edge : 0.9
  link_crash_probability : 0.05
  link_resurrection_probability : 0.3

applications:
  "Siotec2022" :
    filename : siotec.pl # application's Prolog definition
    orchestration_id: arOrch # orchestration id
    trigger_event: event1 # trigger event
    guards :
      fDCC : 0.7
  "Media Processing" :
    filename : media_processing.pl
    orchestration_id: mediaOrch
    trigger_event: event2
    guards :
      fPayAppr : 0.4
  "Stock Market" :
    filename : stock_market.pl
    orchestration_id: stockOrch
    trigger_event: event2
    guards : {}
  
